/* eslint-disable @typescript-eslint/no-var-requires */
const { withTV } = require('tailwind-variants/dist/transformer')
const { fontFamily } = require('tailwindcss/defaultTheme')

/** @type {import('tailwindcss').Config} */
const TAILWIND_CONFIG = {
  darkMode: ['class'],
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    screens: {
      sm: '375px',
      md: '481px',
      lg: '821px',
      xl: '1024px',
    },
    extend: {
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
      fontSize: {
        h1: ['var(--font-size-h1)', 'var(--line-height-h1)'],
        h2: ['var(--font-size-h2)', 'var(--line-height-h2)'],
        h3: ['var(--font-size-h3)', 'var(--line-height-h3)'],
        h4: ['var(--font-size-h4)', 'var(--line-height-h4)'],
        h5: ['var(--font-size-h5)', 'var(--line-height-h5)'],
        h6: ['var(--font-size-h6)', 'var(--line-height-h6)'],
        tiny: ['var(--font-size-tiny)', 'var(--line-height-tiny)'],
        body1: ['var(--font-size-body1)', 'var(--line-height-body1)'],
        body2: ['var(--font-size-body2)', 'var(--line-height-body2)'],
        body3: ['var(--font-size-body3)', 'var(--line-height-body3)'],
      },
      fontFamily: {
        sans: ['var(--font-sans)', ...fontFamily.sans],
        serif: [...fontFamily.serif],
        looped: ['var(--font-looped)', ...fontFamily.sans],
      },
      borderColor: {
        DEFAULT: 'var(--border-default)',
        light: 'var(--border-light)',
        medium: 'var(--border-medium)',
        dark: 'var(--border-dark)',
        disable: 'var(--border-disable)',
      },
      backgroundColor: {
        DEFAULT: 'var(--bg-default)',
        white: 'var(--bg-white)',
        light: 'var(--bg-light)',
        dark: 'var(--bg-dark)',
        disable: 'var(--bg-disable)',
      },
      textColor: {
        high: 'var(--text-high)',
        medium: 'var(--text-medium)',
        placeholder: 'var(--text-placeholder)',
        invert: 'var(--text-invert)',
        disable: 'var(--text-disable)',
      },
      boxShadow: {
        DEFAULT: 'var(--shadow-default)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        inner: 'var(--shadow-inner)',
        'focused-error': 'var(--shadow-error)',
      },
      fontWeight: {
        normal: 400,
        bold: 600,
      },
      colors: {
        primary: {
          DEFAULT: 'var(--primary)',
          bg: 'var(--primary-bg)',
          light: 'var(--primary-light)',
          medium: 'var(--primary-medium)',
          dark: 'var(--primary-dark)',
          50: 'var(--primary-50)',
          100: 'var(--primary-100)',
          200: 'var(--primary-200)',
          300: 'var(--primary-300)',
          400: 'var(--primary-400)',
          500: 'var(--primary-500)',
          600: 'var(--primary-600)',
          700: 'var(--primary-700)',
          800: 'var(--primary-800)',
          900: 'var(--primary-900)',
          950: 'var(--primary-950)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          bg: 'var(--secondary-bg)',
          light: 'var(--secondary-light)',
          medium: 'var(--secondary-medium)',
          dark: 'var(--secondary-dark)',
          50: 'var(--secondary-50)',
          100: 'var(--secondary-100)',
          200: 'var(--secondary-200)',
          300: 'var(--secondary-300)',
          400: 'var(--secondary-400)',
          500: 'var(--secondary-500)',
          600: 'var(--secondary-600)',
          700: 'var(--secondary-700)',
          800: 'var(--secondary-800)',
          900: 'var(--secondary-900)',
          950: 'var(--secondary-950)',
        },
        system: {
          info: {
            DEFAULT: 'var(--system-info-default)',
            bg: 'var(--system-info-bg)',
            light: 'var(--system-info-light)',
            medium: 'var(--system-info-medium)',
            dark: 'var(--system-info-dark)',
          },
          success: {
            DEFAULT: 'var(--system-success-default)',
            bg: 'var(--system-success-bg)',
            light: 'var(--system-success-light)',
            medium: 'var(--system-success-medium)',
            dark: 'var(--system-success-dark)',
          },
          error: {
            DEFAULT: 'var(--system-error-default)',
            bg: 'var(--system-error-bg)',
            light: 'var(--system-error-light)',
            medium: 'var(--system-error-medium)',
            dark: 'var(--system-error-dark)',
          },
          warning: {
            DEFAULT: 'var(--system-warning-default)',
            bg: 'var(--system-warning-bg)',
            light: 'var(--system-warning-light)',
            medium: 'var(--system-warning-medium)',
            dark: 'var(--system-warning-dark)',
          },
        },
        yellow: {
          DEFAULT: 'var(--yellow-500)',
          50: 'var(--yellow-50)',
          100: 'var(--yellow-100)',
          200: 'var(--yellow-200)',
          300: 'var(--yellow-300)',
          400: 'var(--yellow-400)',
          500: 'var(--yellow-500)',
          600: 'var(--yellow-600)',
          700: 'var(--yellow-700)',
          800: 'var(--yellow-800)',
          900: 'var(--yellow-900)',
          950: 'var(--yellow-950)',
        },
        pink: {
          DEFAULT: 'var(--pink-500)',
          50: 'var(--pink-50)',
          100: 'var(--pink-100)',
          200: 'var(--pink-200)',
          300: 'var(--pink-300)',
          400: 'var(--pink-400)',
          500: 'var(--pink-500)',
          600: 'var(--pink-600)',
          700: 'var(--pink-700)',
          800: 'var(--pink-800)',
          900: 'var(--pink-900)',
          950: 'var(--pink-950)',
        },
        green: {
          DEFAULT: 'var(--green-500)',
          50: 'var(--green-50)',
          100: 'var(--green-100)',
          200: 'var(--green-200)',
          300: 'var(--green-300)',
          400: 'var(--green-400)',
          500: 'var(--green-500)',
          600: 'var(--green-600)',
          700: 'var(--green-700)',
          800: 'var(--green-800)',
          900: 'var(--green-900)',
          950: 'var(--green-950)',
        },
        blue: {
          DEFAULT: 'var(--blue-500)',
          50: 'var(--blue-50)',
          100: 'var(--blue-100)',
          200: 'var(--blue-200)',
          300: 'var(--blue-300)',
          400: 'var(--blue-400)',
          500: 'var(--blue-500)',
          600: 'var(--blue-600)',
          700: 'var(--blue-700)',
          800: 'var(--blue-800)',
          900: 'var(--blue-900)',
          950: 'var(--blue-950)',
        },
        orange: {
          DEFAULT: 'var(--orange-500)',
          50: 'var(--orange-50)',
          100: 'var(--orange-100)',
          200: 'var(--orange-200)',
          300: 'var(--orange-300)',
          400: 'var(--orange-400)',
          500: 'var(--orange-500)',
          600: 'var(--orange-600)',
          700: 'var(--orange-700)',
          800: 'var(--orange-800)',
          900: 'var(--orange-900)',
          950: 'var(--orange-950)',
        },
        purple: {
          DEFAULT: 'var(--purple-500)',
          50: 'var(--purple-50)',
          100: 'var(--purple-100)',
          200: 'var(--purple-200)',
          300: 'var(--purple-300)',
          400: 'var(--purple-400)',
          500: 'var(--purple-500)',
          600: 'var(--purple-600)',
          700: 'var(--purple-700)',
          800: 'var(--purple-800)',
          900: 'var(--purple-900)',
          950: 'var(--purple-950)',
        },
        red: {
          DEFAULT: 'var(--red-500)',
          50: 'var(--red-50)',
          100: 'var(--red-100)',
          200: 'var(--red-200)',
          300: 'var(--red-300)',
          400: 'var(--red-400)',
          500: 'var(--red-500)',
          600: 'var(--red-600)',
          700: 'var(--red-700)',
          800: 'var(--red-800)',
          900: 'var(--red-900)',
          950: 'var(--red-950)',
        },
        neutral: {
          DEFAULT: 'var(--neutral-500)',
          0: 'var(--neutral-000)',
          50: 'var(--neutral-050)',
          100: 'var(--neutral-100)',
          200: 'var(--neutral-200)',
          300: 'var(--neutral-300)',
          400: 'var(--neutral-400)',
          500: 'var(--neutral-500)',
          600: 'var(--neutral-600)',
          700: 'var(--neutral-700)',
          800: 'var(--neutral-800)',
          900: 'var(--neutral-900)',
          950: 'var(--neutral-950)',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
    },
  },
  plugins: [
    require('tailwindcss-animate'),
    require('tailwind-scrollbar-hide'),
    ({ addUtilities }) => {
      addUtilities({
        '.h1': {
          '@apply text-h1 font-sans': {},
        },
        '.h2': {
          '@apply text-h2 font-sans': {},
        },
        '.h3': {
          '@apply text-h3 font-sans': {},
        },
        '.h4': {
          '@apply text-h4 font-sans': {},
        },
        '.h5': {
          '@apply text-h5 font-sans': {},
        },
        '.h6': {
          '@apply text-h6 font-sans': {},
        },
        '.tiny': {
          '@apply text-tiny font-sans': {},
        },
        '.body1': {
          '@apply text-body1 font-looped': {},
        },
        '.body2': {
          '@apply text-body2 font-looped': {},
        },
        '.body3': {
          '@apply text-body3 font-looped': {},
        },
      })
    },
  ],
}

module.exports = withTV(TAILWIND_CONFIG)
