version: "3.9"

services:
  banana-frontend:
    build: ./frontend
    container_name: banana-frontend
    ports:
      - 3000:3000

  banana-realtime-chat-backend:
    build: ./realtime-chat-backend
    container_name: banana-realtime-chat-backend
    ports:
      - 9000:9000
