version: '3.9'

services:
  banana-db:
    container_name: banana-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: banana
      POSTGRES_DB: banana-db
