const TOAST_LIMIT = 1
const TOAST_REMOVE_DELAY = 100000
const TOAST_ACTION_TYPES = {
  ADD_TOAST: 'ADD_TOAST',
  UPDATE_TOAST: 'UPDATE_TOAST',
  DISMISS_TOAST: 'DISMISS_TOAST',
  REMOVE_TOAST: 'REMOVE_TOAST',
} as const

export { TOAST_ACTION_TYPES, TOAST_LIMIT, TOAST_REMOVE_DELAY }
